version: '3.8'

services:
  nestjs_api:
    build: 
      context: .
      dockerfile: dockerfile
    ports: 
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=development
    volumes: 
      - ./src:/app/src

  prisma_migrate:
    image: node:20
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    entrypoint: ["sh", "-c", "until pg_isready -h postgres -p 5432; do echo waiting for postgres; sleep 2; done; npx prisma migrate dev --name init"]
